#!/usr/bin/python3

import socket
import pickle
import pymongo
import subprocess


myclient = pymongo.MongoClient("mongodb://localhost:27017/")
mydb = myclient["test_h"]
mycol = mydb["data"]


HEADERSIZE = 100

ip = socket.gethostname()
port = 55555

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((ip, port))

count = 0

while True:
	full_msg = b''
	new_msg = True
	while True:
		msg = s.recv(5)
		count += 1
		if len(msg) <= 0:
			break
		if new_msg:
			msglen = int(msg[:HEADERSIZE])
			new_msg = False
		full_msg += msg

		if len(full_msg) - HEADERSIZE == msglen:
			print("full msg received")
			msg_got = pickle.loads(full_msg[HEADERSIZE:])
			print("command got : ", msg_got)
			# x = os.popen(msg_got).read()
			# print(x)
			try:
				do_command = subprocess.check_output(msg_got, shell=True)
				print(do_command)
				if len(do_command.decode()) >= 1:
					to_db = mycol.insert_one({"data": do_command.decode(), "code": 0})
				else:
					to_db = mycol.insert_one({"data": "command has no shown value", "code": 0})

			except:
				to_db = mycol.insert_one({"data": "failed command", "code": 0})

			print("number of packets got : ", count)
			count = 0
			break
